### ISSUE TITLE
бесит, но помочь надо...

### ISSUE THREAD

**Issue by MihailNenahov** [ZhidkovGV/BSUIR_BOYZ#1]
я долбоёб и не могу разобраться gite. Хотелось, чтоб ты показал что надо скачать, как скачать. А то немного нихуя не выходит. Не ясно, как это всё работает и всё такое.

**Comment by ZhidkovGV** [comment]
Окей. Завтра вечером могу сделать стрим где все покажу наверное

**Comment by ZhidkovGV** [comment]
Ну и чекни файл с заданием. Там я вроде просто расписал что делать

**Comment by AntonProtopopov** [comment]
жиза, вроде делаю все по инструкции, но вылезают ошибки непонятные мне и все, наши полномочия здесь окончены

**Comment by ZhidkovGV** [comment]
Проблему понял. Завтра в 6 будет стримец. Там обсудим все траблы которые возникли
